version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-jwt-auth-nodejs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r3wf7rt6ikj8"
s3_prefix = "aws-sam-jwt-auth-nodejs"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
