AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-jwt-auth

  Sample SAM Template for sam-jwt-auth

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  WhiteListAllIPsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all traffic
      SecurityGroupIngress:
        - IpProtocol: tcp, udp, icmp, icmpv6
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp, udp, icmp, icmpv6
          CidrIp: 0.0.0.0/0

  ConnectToMongoDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/
      Handler: app.connectToMongoDB
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        UploadImageEvent:
          Type: Api
          Properties:
            Path: /connect-db
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - !Ref WhiteListAllIPsSecurityGroup

Outputs:
  ConnectToMongoDBApi:
    Description: "API Gateway endpoint URL for Prod stage for ConnectToMongoDB function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/connect-db/"
  ConnectToMongoDBFunction:
    Description: "ConnectToMongoDB Lambda Function ARN"
    Value: !GetAtt ConnectToMongoDBFunction.Arn
  ConnectToMongoDBFunctionIamRole:
    Description: "Implicit IAM Role created for ConnectToMongoDB function"
    Value: !GetAtt ConnectToMongoDBFunctionRole.Arn
